name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      run: |
        docker build . --file Dockerfile --tag demo
        docker run demo dpkg --print-architecture
